# Generated by Django 4.2.13 on 2026-05-29 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('active_reporting_year', models.IntegerField(default=2024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(help_text='e.g. diesel_combustion, grid_electricity_IN', max_length=100)),
                ('source', models.CharField(choices=[('ipcc', 'IPCC AR6'), ('defra', 'DEFRA UK'), ('epa', 'US EPA'), ('iea', 'IEA Grid'), ('custom', 'Custom')], max_length=20)),
                ('year', models.IntegerField()),
                ('factor_kg_co2e_per_unit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('unit', models.CharField(help_text='Unit of activity (e.g. litre, kWh, km)', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('activity_type', 'source', 'year')},
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_row_id', models.CharField(blank=True, help_text='Identifier in source system (SAP doc number, meter+period, booking ref)', max_length=255)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Export'), ('utility', 'Utility Portal'), ('travel', 'Corporate Travel')], max_length=20)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 – Direct'), ('2_location', 'Scope 2 – Location-based'), ('2_market', 'Scope 2 – Market-based'), ('3', 'Scope 3 – Value chain')], max_length=20)),
                ('scope3_category', models.CharField(blank=True, choices=[('', 'N/A'), ('cat1_purchased_goods', 'Cat 1: Purchased goods & services'), ('cat4_upstream_transport', 'Cat 4: Upstream transport'), ('cat6_business_travel', 'Cat 6: Business travel'), ('cat7_employee_commuting', 'Cat 7: Employee commuting')], default='', max_length=50)),
                ('activity_type', models.CharField(choices=[('diesel_combustion', 'Diesel combustion'), ('petrol_combustion', 'Petrol combustion'), ('natural_gas_combustion', 'Natural gas combustion'), ('grid_electricity', 'Grid electricity consumption'), ('flight', 'Flight'), ('hotel_stay', 'Hotel stay'), ('car_rental', 'Car rental'), ('rail_travel', 'Rail travel'), ('procurement_spend', 'Procurement spend')], max_length=50)),
                ('raw_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('raw_unit', models.CharField(max_length=50)),
                ('canonical_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('canonical_unit', models.CharField(max_length=50)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('activity_date', models.DateField(help_text='Date the activity occurred or billing period start')),
                ('period_end', models.DateField(blank=True, help_text='End of billing period if activity spans a range', null=True)),
                ('reporting_year', models.IntegerField()),
                ('location_name', models.CharField(blank=True, help_text='Human-readable location if no plant code', max_length=255)),
                ('country', models.CharField(blank=True, help_text='ISO alpha-2', max_length=2)),
                ('travel_origin', models.CharField(blank=True, help_text='IATA airport/city code', max_length=10)),
                ('travel_destination', models.CharField(blank=True, max_length=10)),
                ('travel_class', models.CharField(blank=True, help_text='economy / business / first (affects flight emission factor)', max_length=20)),
                ('traveler_name', models.CharField(blank=True, max_length=255)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated or provided distance for travel records', max_digits=10, null=True)),
                ('meter_id', models.CharField(blank=True, max_length=100)),
                ('tariff_code', models.CharField(blank=True, max_length=100)),
                ('sap_document_number', models.CharField(blank=True, max_length=50)),
                ('sap_cost_center', models.CharField(blank=True, max_length=20)),
                ('sap_material_group', models.CharField(blank=True, max_length=50)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged – Needs Attention'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reasons', models.JSONField(default=list, help_text='List of strings describing why this record was auto-flagged')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='PlantCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_codes', to='ingestion.client')),
            ],
            options={
                'unique_together': {('client', 'code')},
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Export'), ('utility', 'Utility Portal'), ('travel', 'Corporate Travel')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='raw_uploads/%Y/%m/')),
                ('total_rows', models.IntegerField(default=0)),
                ('success_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('flagged_rows', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed'), ('partial', 'Partial (some rows failed)')], default='processing', max_length=20)),
                ('error_log', models.JSONField(default=list, help_text='List of per-row parsing errors')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.client')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FailedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField(help_text='The raw row as parsed from the source file')),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_row_items', to='ingestion.ingestionbatch')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecordAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('diff', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='ingestion.emissionrecord')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.ingestionbatch'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='ingestion.client'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='emission_factor',
            field=models.ForeignKey(blank=True, help_text='Factor used to calculate co2e_kg', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.emissionfactor'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='plant_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.plantcode'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClientMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('analyst', 'Analyst'), ('admin', 'Admin'), ('auditor', 'Auditor (read-only)')], default='analyst', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ingestion.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['client', 'reporting_year', 'scope'], name='ingestion_e_client__5616ff_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['client', 'review_status'], name='ingestion_e_client__48cab2_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['batch'], name='ingestion_e_batch_i_e7d0fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientmembership',
            unique_together={('user', 'client')},
        ),
    ]
